name: k6 Load Test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
  
      - name: Run local k6 test
        uses: grafana/k6-action@v0.3.0
        with:
          filename: script.js
          # use this flag if you dont have configured in the case ##
          flags: --vus 50 --duration 10s
  